[WIP] Add HiddenFromHelpAttribute
Remora/Remora.Commands pull request #14
Opened 2021-12-21 15:40 UTC by Foxtrek64

Fixes #13 

* [x] Add ability to hide commands/groups from the help service.
* [ ] Add Description property to commands (to mirror Groups)
* [ ] Implement information types
  * [ ] IGroupInfo
    * [ ] GroupInfo
  * [ ] ICommandInfo
    * [ ] CommandInfo
  * [ ] ICommandArgumentInfo
    * [ ] CommandArgumentInfo
  * [ ] IConditionInfo
    * [ ] ConditionInfo
* [ ] Implement CommandInformationService

2021-12-23 15:39 UTC, Nihlus requested changes
Looks good! 

One caveat/question - conditions can be applied to groups and parameters, not just commands. You'll want to look into handling that as well.

2021-12-28 22:49 UTC, Nihlus commented on Remora.Commands/CommandInformation/IConditionPropertyInfo.cs
> +    public interface IConditionPropertyInfo
What's up with this?

2025-01-02 10:44 UTC, Nihlus commented
What's the status of this PR?

2025-01-02 15:49 UTC, Foxtrek64 commented
Last commit was four years ago? Well then.

I would like to revisit this sometime, but I think if I do I'll probably start over, using some of this as inspiration. I'll go ahead and close it for now.

2025-01-02 15:49 UTC, closed without merging